name: Build Env

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      imageName:
        description: '构建镜像的名称'
        required: true
      repoPath:
        description: 'git仓库路径,可空'
        required: false
      dockerFileUrl:
        description: '自定义DockerFile下载路径,可空'
        required: false
      platforms:
        description: '需要构建的平台'
        required: false
        default: linux/amd64,linux/arm64
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Git clone
        run: |
         rm -rf {*,.[^.]*,..?*}
         if [[ "${{ github.event.inputs.repoPath }}" ]] ;then git clone "${{github.event.inputs.repoPath}}" . ; fi
         if [[ "${{ github.event.inputs.dockerFileUrl }}" ]] ;then wget "${{github.event.inputs.dockerFileUrl}}" -O ./Dockerfile ; fi

      # docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 设置 docker 环境
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: Get current date
        id: date
        run: echo "::set-output name=time::$(date +'%m-%d_%H-%M-%S')"

      # build 并且 push docker 镜像
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.imageName }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.imageName }}:${{steps.date.outputs.time}}
          platforms: ${{github.event.inputs.platforms}}
      
      # 打印 docker 镜像 SHA256 Hash 值
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
